import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/contexts/SidebarContext";
import ClientLayout from "@/components/layout/ClientLayout";
import { ThemeProvider } from '@/contexts/ThemeContext';
import Script from 'next/script';
import { MoviesAccessProvider } from '@/contexts/MoviesAccessContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Bảo Mink Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script id="theme-switcher" strategy="beforeInteractive">
          {`
            if (localStorage.theme === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
              document.documentElement.classList.add('dark')
            } else {
              document.documentElement.classList.remove('dark')
            }
          `}
        </Script>
      </head>
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-950`}
      >
        <ThemeProvider>
          <SidebarProvider>
            <MoviesAccessProvider>
              <div className="min-h-screen bg-white dark:bg-gray-950">
                <ClientLayout>{children}</ClientLayout>
              </div>
            </MoviesAccessProvider>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
